name: CI/CD
on:
  push:
    branches: [main]
jobs:
  ci-cd:
    permissions:
      security-events: write
      contents: write
      id-token: write
    uses: tarsilla-app/workflows/.github/workflows/node.yml@main
    with:
      suppression: true
      publish: npm
      deploy: storybook
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}