name: CI/CD
on:
  push:
    branches: [main]
jobs:
  ci-cd:
    permissions:
      security-events: write
      contents: write
      id-token: write
      pages: write
    uses: tarsilla-app/workflows/.github/workflows/node.yml@main
    with:
      suppression: true
      publish: '["library", "npm"]'
      deploy: '["storybook", "github-pages"]'
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
  use-pages-url:
    runs-on: ubuntu-latest
    needs: ci-cd
    environment:
      name: github-pages
      url: ${{ needs.ci-cd.outputs.pages_url }}
    steps:
      - name: Print Pages URL
        run: "echo 'Deployed Pages URL: ${{ needs.ci-cd.outputs.deploy-storybook.pages_url }}'"
      - name: Print Outputs
        run: "echo 'Deployed Pages URL: ${{toJson( needs.ci-cd.outputs) }}'"